name: Codecov

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Taskfile
        uses: arduino/setup-task@v1

      - name: Generate coverage report
        run: task unit

      - name: Upload coverage to Codecov (demo)
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage.txt #./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          
          #file: ./coverage.txt
          #name: codecov-demo
      # - name: Upload coverage to Codecov
      #   run: bash <(curl -s https://codecov.io/bash)