name: test

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # cloning current repo into docker-container

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Taskfile
        uses: arduino/setup-task@v1

      - name: Test account
        run: cd account && task unit-v